#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
rm -rf log.HRMFoam  log.decomposePar log.reconstructPar processor* 
rm -rf 0.[0-9]* *e-0?
#------------------------------------------------------------------------------
