#!/bin/bash
#PBS -P un91 
#PBS -q normal
#PBS -l walltime=4:0:0
#PBS -l ncpus=48
#PBS -l mem=32GB
#PBS -N myFoamRun
#PBS -j oe
#PBS -M your@email.com
#PBS -m ae
#PBS -l wd
#PBS -l storage=scratch/un91

module load intel-compiler-llvm/2025.3.2
module load intel-mpi/2021.17.2
module load metis/5.1.0-i8r8
module load fftw3/3.3.10-nci1
source $HOME/OpenFOAM/OpenFOAM-v2412/etc/bashrc 


cd $PBS_O_WORKDIR
echo Jobid: $PBS_JOBID
echo Running on host `hostname`
echo Running on nodes `cat $PBS_NODEFILE`

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#------------------------------------------------------------------------------

if [ ! -f log.$(getApplication) ] ; then
	# new case
	runApplication setFields
else
	# restarting
	/home/565/djd565/bin/move_logs.sh log.$(getApplication)
fi

runApplication decomposePar
runParallel $(getApplication)

# if successfully completed run, recon timesteps
#runApplication reconstructPar

#------------------------------------------------------------------------------
