#!/bin/bash -l

#SBATCH --job-name=myFoamCase
#SBATCH --time=0-4:00:00
#SBATCH --nodes=2
#SBATCH --ntasks=32
#SBATCH --mem-per-cpu=2048
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=your@email.com
#SBATCH --output=myFoamCase-%j.out


module load openfoam/v2412-intel

which HRMFoam # check which binary we will run

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#------------------------------------------------------------------------------

if [ ! -f log.$(getApplication) ] ; then
	# new case
	runApplication setFields
else
	# restarting
	move_logs.sh log.$(getApplication)
fi

runApplication decomposePar

# For M3
mpirun -np $SLURM_NTASKS $(getApplication) -parallel > log.$(getApplication) 2>&1

# if successfully completed run, recon timesteps
runApplication reconstructPar

#------------------------------------------------------------------------------
